#!/usr/bin/env python3
"""
Report Generation Module
"""

import json
from datetime import datetime

def generate_report(results, format_type='json'):
    """
    Generate a report from analysis results
    
    Args:
        results: Analysis results dictionary
        format_type: 'json' or 'html'
    
    Returns:
        str: Filename of generated report
    """
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    
    if format_type == 'json':
        filename = f"secguard_report_{timestamp}.json"
        with open(filename, 'w') as f:
            json.dump(results, f, indent=4, default=str)
    else:  # HTML
        filename = f"secguard_report_{timestamp}.html"
        html_content = generate_html_report(results)
        with open(filename, 'w') as f:
            f.write(html_content)
    
    return filename

def generate_html_report(results):
    """Generate HTML report"""
    
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>SecGuard Security Report</title>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background: #1a1a2e; color: #eee; }}
            .container {{ max-width: 1000px; margin: auto; background: #16213e; padding: 30px; border-radius: 15px; }}
            h1 {{ color: #e94560; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
            h2 {{ color: #0f3460; background: #e94560; padding: 10px; border-radius: 8px; margin-top: 30px; }}
            .module {{ background: #1a1a2e; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 4px solid #e94560; }}
            table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
            th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #333; }}
            th {{ background: #0f3460; color: #e94560; }}
            tr:hover {{ background: #1a1a2e; }}
            .badge {{ display: inline-block; padding: 3px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; }}
            .success {{ background: #2ecc71; color: #fff; }}
            .warning {{ background: #f39c12; color: #fff; }}
            .danger {{ background: #e74c3c; color: #fff; }}
            .info {{ background: #3498db; color: #fff; }}
            .grade {{ font-size: 48px; font-weight: bold; padding: 10px 20px; border-radius: 10px; }}
            .grade-A {{ background: #2ecc71; color: #fff; }}
            .grade-B {{ background: #2ecc71; color: #fff; }}
            .grade-C {{ background: #f39c12; color: #fff; }}
            .grade-D {{ background: #e67e22; color: #fff; }}
            .grade-F {{ background: #e74c3c; color: #fff; }}
            .footer {{ margin-top: 40px; color: #888; font-size: 12px; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🛡️ SecGuard Security Analysis Report</h1>
            <p><strong>Generated:</strong> {results.get('timestamp', 'N/A')}</p>
            <p><strong>Modules Used:</strong> {', '.join(results.get('modules_used', []))}</p>
            
            {generate_html_modules(results)}
            
            <div class="footer">
                <p>Report generated by SecGuard v1.0 - Defensive Security Analysis Toolkit</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return html_template

def generate_html_modules(results):
    """Generate HTML for each module result"""
    html = ""
    
    if 'log_analysis' in results:
        log = results['log_analysis']
        risk_icon = '✅' if log.get('risk_level', '').startswith('✅') else '⚠️' if log.get('risk_level', '').startswith('⚠️') else '🚨'
        html += f"""
        <div class="module">
            <h2>📊 Log Analysis</h2>
            <p><strong>File:</strong> {log.get('filename', 'N/A')}</p>
            <p><strong>Total Lines:</strong> {log.get('total_lines', 0)}</p>
            <p><strong>Suspicious Events:</strong> {log.get('suspicious_count', 0)}</p>
            <p><strong>Risk Level:</strong> {risk_icon} {log.get('risk_level', 'Unknown')}</p>
            <p><strong>Threat Score:</strong> {log.get('threat_score', 0)}/100</p>
            
            <h3>🔍 Attack Types</h3>
            <table>
                <tr><th>Attack Type</th><th>Count</th></tr>
                {''.join([f"<tr><td>{attack}</td><td>{count}</td></tr>" for attack, count in log.get('attack_types', {}).items()])}
            </table>
            
            <h3>🎯 Top Attackers</h3>
            <table>
                <tr><th>IP Address</th><th>Attempts</th></tr>
                {''.join([f"<tr><td>{ip}</td><td>{count}</td></tr>" for ip, count in list(log.get('top_attackers', {}).items())[:5]])}
            </table>
        </div>
        """
    
    if 'headers_analysis' in results:
        headers = results['headers_analysis']
        grade_class = f"grade-{headers.get('grade', 'F')}"
        html += f"""
        <div class="module">
            <h2>🌐 HTTP Security Headers</h2>
            <p><strong>URL:</strong> {headers.get('url', 'N/A')}</p>
            <p><strong>Grade:</strong> <span class="grade {grade_class}">{headers.get('grade', 'F')}</span></p>
            <p><strong>Score:</strong> {headers.get('score', 0)}%</p>
            
            <h3>📋 Headers Status</h3>
            <table>
                <tr><th>Header</th><th>Status</th><th>Value</th></tr>
                {''.join([f"<tr><td>{header}</td><td>{'✅ Present' if status else '❌ Missing'}</td><td>{headers.get('headers_found', {}).get(header, 'N/A')}</td></tr>" for header, status in headers.get('headers_status', {}).items()])}
            </table>
            
            <h3>💡 Suggestions</h3>
            <ul>
                {''.join([f"<li>{s}</li>" for s in headers.get('suggestions', [])])}
            </ul>
        </div>
        """
    
    if 'metadata_analysis' in results:
        meta = results['metadata_analysis']
        risk_icon = '✅' if meta.get('risk_level', '').startswith('✅') else '⚠️'
        
        # Build EXIF table if exists
        exif_table = ""
        if meta.get('exif_data'):
            exif_rows = ""
            for k, v in meta.get('exif_data', {}).items():
                exif_rows += f"<tr><td>{k}</td><td>{v}</td></tr>"
            exif_table = f"<h3>📷 EXIF Data</h3><table>{exif_rows}</table>"
        
        # Build indicators list
        indicators_html = ""
        if meta.get('indicators'):
            indicators_html = f"<p><strong>Indicators:</strong> {', '.join(meta.get('indicators', []))}</p>"
        
        html += f"""
        <div class="module">
            <h2>📄 File Metadata</h2>
            <p><strong>File:</strong> {meta.get('filename', 'N/A')}</p>
            <p><strong>Size:</strong> {meta.get('size', 'N/A')}</p>
            <p><strong>Type:</strong> {meta.get('file_type', 'N/A')}</p>
            <p><strong>MD5:</strong> <code>{meta.get('md5', 'N/A')}</code></p>
            <p><strong>SHA256:</strong> <code>{meta.get('sha256', 'N/A')}</code></p>
            <p><strong>Risk Level:</strong> {risk_icon} {meta.get('risk_level', 'Unknown')}</p>
            
            <h3>📋 File Details</h3>
            <table>
                <tr><td>Created</td><td>{meta.get('created', 'N/A')}</td></tr>
                <tr><td>Modified</td><td>{meta.get('modified', 'N/A')}</td></tr>
                <tr><td>Accessed</td><td>{meta.get('accessed', 'N/A')}</td></tr>
            </table>
            
            {exif_table}
            {indicators_html}
        </div>
        """
    
    if 'password_analysis' in results:
        pwd = results['password_analysis']
        strength_class = 'success' if pwd.get('score', 0) >= 60 else 'warning' if pwd.get('score', 0) >= 40 else 'danger'
        
        # Build issues list
        issues_html = ""
        if pwd.get('issues'):
            issues_items = ''.join([f"<li>{issue}</li>" for issue in pwd.get('issues', [])])
            issues_html = f"<h3>⚠️ Issues</h3><ul>{issues_items}</ul>"
        
        # Build suggestions list
        suggestions_html = ""
        if pwd.get('suggestions'):
            suggestions_items = ''.join([f"<li>{s}</li>" for s in pwd.get('suggestions', [])])
            suggestions_html = f"<h3>💡 Suggestions</h3><ul>{suggestions_items}</ul>"
        
        html += f"""
        <div class="module">
            <h2>🔐 Password Analysis</h2>
            <p><strong>Password:</strong> {pwd.get('password', 'N/A')}</p>
            <p><strong>Strength:</strong> <span class="badge {strength_class}">{pwd.get('strength', 'N/A')}</span></p>
            <p><strong>Score:</strong> {pwd.get('score', 0)}/100</p>
            <p><strong>Length:</strong> {pwd.get('length', 0)} characters</p>
            <p><strong>Est. Crack Time:</strong> {pwd.get('crack_time', 'N/A')}</p>
            <p><strong>Entropy:</strong> {pwd.get('entropy', 'N/A')} bits</p>
            
            {issues_html}
            {suggestions_html}
        </div>
        """
    
    return html